Evara/Areas/Admin/Controllers/CategoryController.cs
using Evara.Data;
using Evara.Models;
using Microsoft.AspNetCore.Mvc;

namespace Evara.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _db;

        public CategoryController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            if (!User.IsInRole("Admin"))
            {
                return RedirectToAction("Login", "Account", new { area = "Identity" });
            }
            IEnumerable<Category> categories = _db.Categories.ToList();
            return View(categories);
        }
        [HttpGet]
        public IActionResult Upsert(int id)
        {
            Category category = new Category();
            if (id == 0)
            {
                return View(category);
            }
            category = _db.Categories.FirstOrDefault(i => i.CategoryID == id);
            return View(category);
        }

        [HttpPost]
        public IActionResult Upsert(Category categories)
        {
            if (ModelState.IsValid)
            {
                if (categories.CategoryID == 0)
                {
                    _db.Categories.Add(categories);
                }
                else
                {
                    _db.Categories.Update(categories);
                }
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Evara/Areas/Customer/Controllers/ShopController.cs
using Evara.Data;
using Evara.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Evara.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class ShopController : Controller
    {
        private readonly ApplicationDbContext _db;
        public ShopController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            int pageSize = 6;
            IEnumerable<Product> products = _db.Products.Include(sp => sp.Category);
            ViewBag.TotalPages = products.Count() / pageSize + 1;
            return View(products);
        }

        [HttpPost]
        public IActionResult GetProduct()
        {
            IEnumerable<Product> products = _db.Products.Include(sp => sp.Category);
            return Json(new { data = products });
        }

        public IActionResult Detail(int id)
        {
            IEnumerable<String> sizes = _db.Products.Where(sp => sp.ProductID == id).Select(sp => sp.Size);
            ViewBag.Size = sizes;
            Product product = _db.Products.Include(sp => sp.Brand).Include(sp => sp.Category).FirstOrDefault(sp => sp.ProductID == id);
            IEnumerable<Product> relatedProduct = _db.Products.Where(sp => sp.CategoryID == product.CategoryID && sp.ProductID != product.ProductID).ToList();
            if(relatedProduct.Count() == 0)
            {
                relatedProduct = _db.Products.Where(sp => sp.BrandID == product.BrandID && sp.ProductID != product.ProductID).ToList();
            }
            ViewBag.RelatedProduct = relatedProduct;
            return View(product);
        }

        public IActionResult Cart()
        {
            return View();
        }

        public IActionResult CheckOut()
        {
            return View();
        }
    }
}

Evara/Areas/Customer/Views/Shop/Detail.cshtml
@model Product

<main class="main">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a asp-action="Index" asp-controller="Home" rel="nofollow">Home</a>
                <span></span>
                <a asp-action="Index" rel="nofollow">Shop</a>
                <span></span> @Model.Category.Name
            </div>
        </div>
    </div>
    <section class="mt-50 mb-50">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="product-detail accordion-detail">
                        <div class="row mb-50">
                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <div class="detail-gallery">
                                    <!-- MAIN SLIDES -->
                                    <div class="product-image-slider">
                                        <img src="@Model.ImagePath" alt="product image" class="border-radius-10">
                                    </div>
                                    <!-- THUMBNAILS -->
                                    <div class="slider-nav-thumbnails pl-15 pr-15">
                                        <div><img src="@Model.ImagePath" alt="product image"></div>
                                    </div>
                                </div>
                                <!-- End Gallery -->
                            </div>
                            <div class="col-md-6 col-sm-12 col-xs-12">
                                <div class="detail-info">
                                    <h2 class="title-detail">@Model.Name</h2>
                                    <div class="product-detail-rating">
                                        <div class="pro-details-brand">
                                            <span> Brands: <a href="shop-grid-right.html">@Model.Brand.Name</a></span>
                                        </div>
                                    </div>
                                    <div class="clearfix product-price-cover">
                                        <div class="product-price primary-color float-left">
                                            <ins><span class="text-brand">@Model.Price$</span></ins>
                                        </div>
                                    </div>
                                    <div class="bt-1 border-color-1 mt-15 mb-15"></div>
                                    <div class="product_sort_info font-xs mb-30">
                                        <ul>
                                            <li class="mb-10"><i class="fi-rs-crown mr-5"></i> 1 Year Warranty</li>
                                            <li class="mb-10"><i class="fi-rs-refresh mr-5"></i> 30 Day Return Policy</li>
                                            <li><i class="fi-rs-credit-card mr-5"></i> Cash on Delivery available</li>
                                        </ul>
                                    </div>
                                    <div class="attr-detail attr-size">
                                        <strong class="mr-10">Size</strong>
                                        <ul class="list-filter size-filter font-small">
                                            @{
            /*foreach (var size in ViewBag.sizes)
                                                {
                                                <li><a href="#">@size</a></li>
                                                }*/
                                            }
                                        </ul>
                                    </div>
                                    <div class="bt-1 border-color-1 mt-30 mb-30"></div>
                                    <div class="detail-extralink">
                                        <div class="detail-qty border radius">
                                            <a href="#" class="qty-down"><i class="fi-rs-angle-small-down"></i></a>
                                            <span class="qty-val">1</span>
                                            <a href="#" class="qty-up"><i class="fi-rs-angle-small-up"></i></a>
                                        </div>
                                        <div class="product-extra-link2">
                                            <button type="submit" class="button button-add-to-cart">Add to cart</button>
                                        </div>
                                    </div>
                                    <ul class="product-meta font-xs color-grey mt-50">
                                        <li class="mb-5">Tags: <a asp-controller="Category" asp-action="Index" asp-route-id="@Model.CategoryID" rel="tag">@Model.Category.Name</a></li>
                                    </ul>
                                </div>
                                <!-- Detail Info -->
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-10 m-auto entry-main-content">
                                <h2 class="section-title style-1 mb-30">Description</h2>
                                <div class="description mb-50">
                                    <p>
                                        @Model.Description
                                    </p>
                                    <h4 class="mt-30">Packaging & Delivery</h4>
                                    <hr class="wp-block-separator is-style-wide">
                                    <p>
                                        Less lion goodness that euphemistically robin expeditiously bluebird smugly scratched far while thus cackled sheepishly rigid after due one assenting regarding censorious while occasional or this more crane
                                        went more as this less much amid overhung anathematic because much held one exuberantly sheep goodness so where rat wry well concomitantly.
                                    </p>
                                    <p>
                                        Scallop or far crud plain remarkably far by thus far iguana lewd precociously and and less rattlesnake contrary caustic wow this near alas and next and pled the yikes articulate about as less cackled dalmatian
                                        in much less well jeering for the thanks blindly sentimental whimpered less across objectively fanciful grimaced wildly some wow and rose jeepers outgrew lugubrious luridly irrationally attractively
                                        dachshund.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="row mt-60">
                            <div class="col-12">
                                <h3 class="section-title style-1 mb-30">Related products</h3>
                            </div>
                            <div class="col-12">
                                <div class="row related-products">
                                    @foreach(Product product in ViewBag.RelatedProduct)
                                    {
                                        <div class="col-lg-3 col-md-4 col-12 col-sm-6">
                                        <div class="product-cart-wrap small hover-up">
                                            <div class="product-img-action-wrap">
                                                <div class="product-img product-img-zoom">
                                                    <a asp-controller="Shop" asp-action="Detail" asp-route-id="@product.ProductID" tabindex="0">
                                                        <img class="default-img" src="@product.ImagePath" alt="">
                                                    </a>
                                                </div>
                                            </div>
                                            <div class="product-content-wrap">
                                                <h2><a asp-controller="Shop" asp-action="Detail" tabindex="0">@product.Name</a></h2>
                                                <div class="product-price">
                                                    <span>@product.Price</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    }
                                </div>
                            </div>
                        </div>
                        <div class="banner-img banner-big wow fadeIn f-none animated mt-50">
                            <img class="border-radius-10" src="~/imgs/banner/banner-4.png" alt="">
                            <div class="banner-text">
                                <h4 class="mb-15 mt-40">Repair Services</h4>
                                <h2 class="fw-600 mb-20">We're an Apple <br>Authorised Service Provider</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>

Evara/Areas/Customer/Views/Shop/Index.cshtml
@model IEnumerable<Product>
<main class="main">
    <div class="page-header breadcrumb-wrap">
        <div class="container">
            <div class="breadcrumb">
                <a href="index.html" rel="nofollow">Home</a>
                <span></span> Shop
            </div>
        </div>
    </div>
    <section class="mt-50 mb-50">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="shop-product-fillter">
                        <div class="totall-product">
                            <p> We found <strong class="text-brand">@Model.Count()</strong> items for you!</p>
                        </div>
                        <div class="sort-by-product-area">
                            <div class="sort-by-cover mr-10">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps"></i>Show:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">50</a></li>
                                        <li><a href="#">100</a></li>
                                        <li><a href="#">150</a></li>
                                        <li><a href="#">200</a></li>
                                        <li><a href="#">All</a></li>
                                    </ul>
                                </div>
                            </div>
                            <div class="sort-by-cover">
                                <div class="sort-by-product-wrap">
                                    <div class="sort-by">
                                        <span><i class="fi-rs-apps-sort"></i>Sort by:</span>
                                    </div>
                                    <div class="sort-by-dropdown-wrap">
                                        <span> Featured <i class="fi-rs-angle-small-down"></i></span>
                                    </div>
                                </div>
                                <div class="sort-by-dropdown">
                                    <ul>
                                        <li><a class="active" href="#">Featured</a></li>
                                        <li><a href="#">Price: Low to High</a></li>
                                        <li><a href="#">Price: High to Low</a></li>
                                        <li><a href="#">Release Date</a></li>
                                        <li><a href="#">Avg. Rating</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row product-grid-3">
                        @foreach (var product in Model)
                        {
                            <div class="col-lg-3 col-md-4">
                                <div class="product-cart-wrap mb-30">
                                    <div class="product-img-action-wrap">
                                        <div class="product-img product-img-zoom">
                                            <a asp-action="Detail" asp-route-id="@product.ProductID">
                                                <img class="default-img" src="@product.ImagePath" alt="">
                                            </a>
                                        </div>
                                    </div>
                                    <div class="product-content-wrap">
                                        <div class="product-category">
                                            <a asp-action="Detail" asp-route-id="@product.ProductID">@product.Category.Name</a>
                                        </div>
                                        <h2><a asp-action="Detail" asp-route-id="@product.ProductID">@product.Name</a></h2>
                                        <div class="product-price">
                                            <span>@product.Price$</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                    <!--pagination-->
                    <div class="pagination-area mt-15 mb-sm-5 mb-lg-0">
                        <nav aria-label="Page navigation example">
                            <ul class="pagination justify-content-start">
                                @for (int i = 1; i <= ViewBag.TotalPages; i++)
                                {
                                    <li class="page-item">
                                        <a class="page-link" href="#" onclick="Page.Paging(@i)">@i</a>
                                    </li>
                                }
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
<partial name="_PagingScript" />